### ISSUE TITLE
Not showing Run button

### ISSUE THREAD

**Issue by gandhidarshak** [Pencilcaseman/codeblock-runner#1]
I followed the steps and installed/enabled the plugin manually. I am not able to see the run button plug-in still. What am I missing?

![image](https://user-images.githubusercontent.com/36289431/220176777-51872bcc-c972-4941-a1e6-4d4c9752dacf.png)

![image](https://user-images.githubusercontent.com/36289431/220176704-713b07b2-40de-4aa7-ab2a-15ec5bfdbbc7.png)

**Comment by aparente** [comment]
having the same problem :(

**Comment by Pencilcaseman** [comment]
Make sure you're in Reading Mode, not Editing Mode. If that doesn't fix it, could you give me a few more details?

**Comment by Pencilcaseman** [comment]
I will now close this issue, but if you still have issues, please feel free to re-open it.
